platform :ios, '11.0'
use_frameworks!

target 'Example' do
  # The Example uses the bundled StripeTerminal.xcframework. Uncomment this line
  # to install the framework via cocoapods in your project.
  # pod 'StripeTerminal', '~>2.0'
  pod 'Alamofire', '~> 5.0'
  pod 'Static', inhibit_warnings: true, git: 'https://github.com/venmo/Static', tag: 'v4.0.0'
end

# Set deployment target to 11.0, minimum required by Stripe Terminal
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
