platform :ios, '13.0'
use_frameworks!

target 'Example' do
  # The Example uses the bundled StripeTerminal.xcframework. Uncomment this line
  # to install the framework via cocoapods in your project.
  # pod 'StripeTerminal', '~>2.0'
  pod 'Alamofire', '~> 5.0'
  pod 'Static', inhibit_warnings: true, git: 'https://github.com/venmo/Static', tag: 'v4.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Set deployment target to 13.0, minimum required by Stripe Terminal
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # Suppress warnings from any of the pods we depend on.
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
    end
  end
end
