//
//  SCPRefund.h
//  StripeTerminal
//
//  Created by James Little on 2/20/20.
//  Copyright © 2020 Stripe. All rights reserved.
//
//  Use of this SDK is subject to the Stripe Terminal Terms:
//  https://stripe.com/terminal/legal
//
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/**
 The possible statuses for a refund.

 @see https://stripe.com/docs/api/refunds/object#refund_object-status
 */
typedef NS_ENUM(NSUInteger, SCPRefundStatus) {
    /**
     The refund succeeded.
     */
    SCPRefundStatusSucceeded,

    /**
     The refund is pending.
     */
    SCPRefundStatusPending,

    /**
     The refund failed.
     */
    SCPRefundStatusFailed,

    /**
     Unknown refund state.
     */
    SCPRefundStatusUnknown,

    /**
     The refund was canceled.
     */
    SCPRefundStatusCanceled,

    /**
     The refund requires an additional action to continue processing.
     */
    SCPRefundStatusRequiresAction,
} NS_SWIFT_NAME(RefundStatus);

@class SCPPaymentMethodDetails, SCPRefundNextAction;

/**
 An object representing a Stripe refund.

 Some payment methods, like Interac Debit payments, require that in-person payments
 also be refunded while the cardholder is present. The cardholder must present
 the Interac card to the card reader; these payments cannot be refunded via the
 dashboard or the API.

 @see https://stripe.com/docs/terminal/canada#interac-refunds

 The SDK returns this object for both in-person refunds and Refunds created
 without collecting a payment method. Use `processRefund` for payment methods
 that require in-person collection.

 @see https://stripe.com/docs/api#refunds
 */
NS_SWIFT_NAME(Refund)
@interface SCPRefund : NSObject

/**
 The unique identifier for the Refund, if one has been assigned by Stripe.
 */
@property (nonatomic, nullable, readonly) NSString *stripeId;

/**
 The amount that was refunded.
 */
@property (nonatomic, readonly) NSUInteger amount;

/**
 The ID of the charge that was refunded
 */
@property (nonatomic, nullable, readonly) NSString *chargeId;

/**
 When the refund object was created.
 */
@property (nonatomic, readonly) NSDate *created;

/**
 The currency of the amount refunded.
 */
@property (nonatomic, readonly) NSString *currency;

/**
 Metadata associated with the refund.

 @see https://stripe.com/docs/api#metadata
 */
@property (nonatomic, readonly) NSDictionary<NSString *, NSString *> *metadata;

/**
 Reason for the refund, either user-provided (`duplicate`, `fraudulent`, or
 `requested_by_customer`) or generated by Stripe internally
 (`expired_uncaptured_charge`).
 */
@property (nonatomic, nullable, readonly) NSString *reason;

/**
 The status of the refund.
 */
@property (nonatomic, readonly) SCPRefundStatus status;

/**
 The action required to continue processing the Refund when its status is
 `SCPRefundStatusRequiresAction`.
 */
@property (nonatomic, nullable, readonly) SCPRefundNextAction *nextAction;

/**
 The payment method details associated with the refund.
 */
@property (nonatomic, nullable, readonly) SCPPaymentMethodDetails *paymentMethodDetails;

/**
 If the refund failed, the reason for refund failure if known.
 */
@property (nonatomic, nullable, readonly) NSString *failureReason;

/**
 Balance transaction that describes the impact of this refund on your account balance.
 */
@property (nonatomic, nullable, readonly) NSString *balanceTransaction;

/**
 An arbitrary string attached to the object. Often useful for displaying to users.
 */
@property (nonatomic, nullable, readonly) NSString *stripeDescription;

/**
 If the refund failed, this balance transaction describes the adjustment made to your account balance that reverses the initial balance transaction.
 */
@property (nonatomic, nullable, readonly) NSString *failureBalanceTransaction;

/**
 ID of the PaymentIntent that was refunded.
 */
@property (nonatomic, nullable, readonly) NSString *paymentIntentId;

/**
 This is the transaction number that appears on email receipts sent for this refund.
 */
@property (nonatomic, nullable, readonly) NSString *receiptNumber;

/**
 The transfer reversal that is associated with the refund. Only present if the charge came from another Stripe account.
 */
@property (nonatomic, nullable, readonly) NSString *sourceTransferReversal;

/**
 If the accompanying transfer was reversed, the transfer reversal object. Only applicable if the charge was created using the destination parameter.
 */
@property (nonatomic, nullable, readonly) NSString *transferReversal;

/**
 You cannot directly instantiate this class.
 */
- (instancetype)init NS_UNAVAILABLE;

/**
 You cannot directly instantiate this class.
 */
+ (instancetype)new NS_UNAVAILABLE;

@end

NS_ASSUME_NONNULL_END
